# El modulo numpy

In [1]:
# importamos el modulo
import numpy as np

In [2]:
# Documentacion del modulo numpy
help(np)

Output hidden; open in https://colab.research.google.com to view.

In [3]:
# Submodulo random
help(np.random)

Help on package numpy.random in numpy:

NAME
    numpy.random

DESCRIPTION
    Random Number Generation
    
    Use ``default_rng()`` to create a `Generator` and call its methods.
    
    =============== =========================================================
    Generator
    --------------- ---------------------------------------------------------
    Generator       Class implementing all of the random number distributions
    default_rng     Default constructor for ``Generator``
    =============== =========================================================
    
    ============================================= ===
    BitGenerator Streams that work with Generator
    --------------------------------------------- ---
    MT19937
    PCG64
    PCG64DXSM
    Philox
    SFC64
    ============================================= ===
    
    ============================================= ===
    Getting entropy to initialize a BitGenerator
    --------------------------------------------

In [4]:
# Submodulo linalg
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    ``numpy.linalg``
    
    The NumPy linear algebra functions rely on BLAS and LAPACK to provide efficient
    low level implementations of standard linear algebra algorithms. Those
    libraries may be provided by NumPy itself using C versions of a subset of their
    reference implementations but, when possible, highly optimized libraries that
    take advantage of specialized processor functionality are preferred. Examples
    of such libraries are OpenBLAS, MKL (TM), and ATLAS. Because those libraries
    are multithreaded and processor dependent, environmental variables and external
    packages such as threadpoolctl may be needed to control the number of threads
    or specify the processor architecture.
    
    - OpenBLAS: https://www.openblas.net/
    - threadpoolctl: https://github.com/joblib/threadpoolctl
    
    Please note that the most-used linear algebra functions in NumPy are present in
    t

In [5]:
# Submodulo fft
help(np.fft)

Help on package numpy.fft in numpy:

NAME
    numpy.fft

DESCRIPTION
    Discrete Fourier Transform (:mod:`numpy.fft`)
    
    .. currentmodule:: numpy.fft
    
    The SciPy module `scipy.fft` is a more comprehensive superset
    of ``numpy.fft``, which includes only a basic set of routines.
    
    Standard FFTs
    -------------
    
    .. autosummary::
       :toctree: generated/
    
       fft       Discrete Fourier transform.
       ifft      Inverse discrete Fourier transform.
       fft2      Discrete Fourier transform in two dimensions.
       ifft2     Inverse discrete Fourier transform in two dimensions.
       fftn      Discrete Fourier transform in N-dimensions.
       ifftn     Inverse discrete Fourier transform in N dimensions.
    
    Real FFTs
    ---------
    
    .. autosummary::
       :toctree: generated/
    
       rfft      Real discrete Fourier transform.
       irfft     Inverse real discrete Fourier transform.
       rfft2     Real discrete Fourier tran

In [6]:
# Submodulo polynomial
help(np.polynomial)

Help on package numpy.polynomial in numpy:

NAME
    numpy.polynomial - A sub-package for efficiently dealing with polynomials.

DESCRIPTION
    Within the documentation for this sub-package, a "finite power series,"
    i.e., a polynomial (also referred to simply as a "series") is represented
    by a 1-D numpy array of the polynomial's coefficients, ordered from lowest
    order term to highest.  For example, array([1,2,3]) represents
    ``P_0 + 2*P_1 + 3*P_2``, where P_n is the n-th order basis polynomial
    applicable to the specific module in question, e.g., `polynomial` (which
    "wraps" the "standard" basis) or `chebyshev`.  For optimal performance,
    all operations on polynomials, including evaluation at an argument, are
    implemented as operations on the coefficients.  Additional (module-specific)
    information can be found in the docstring for the module of interest.
    
    This package provides *convenience classes* for each of six different kinds
    of polynomia

In [7]:
# Lista de elementos/componentes del modulo numpy ( alias np )
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [8]:
# Lista de elementos/componentes del submodulo random
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

In [9]:
# Documentacion de la funcion randint
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer t

In [10]:
# Generemos un numero  aleatorio en [0,9]
np.random.randint(10)

5

In [13]:
# Generemos 666 numeros aleatorios en [33,66]
x = np.random.randint(33,66+1, size = 666)
x

array([36, 41, 63, 52, 64, 45, 35, 39, 61, 50, 48, 49, 47, 59, 64, 37, 39,
       44, 64, 33, 45, 66, 52, 53, 33, 52, 43, 50, 51, 34, 55, 34, 40, 62,
       59, 54, 52, 40, 41, 46, 37, 55, 55, 41, 65, 55, 61, 50, 51, 58, 38,
       43, 66, 65, 38, 66, 35, 44, 52, 33, 58, 58, 55, 38, 60, 42, 39, 55,
       41, 66, 42, 62, 35, 34, 38, 54, 55, 61, 41, 33, 60, 35, 61, 61, 39,
       47, 66, 61, 60, 57, 61, 51, 42, 48, 59, 49, 48, 50, 58, 54, 47, 63,
       66, 57, 60, 41, 49, 53, 62, 48, 61, 52, 60, 38, 40, 45, 61, 41, 55,
       62, 61, 62, 37, 52, 60, 49, 34, 55, 55, 52, 35, 55, 46, 40, 62, 66,
       36, 34, 42, 49, 56, 41, 65, 62, 52, 66, 60, 64, 34, 36, 64, 48, 33,
       65, 38, 39, 64, 62, 41, 37, 34, 63, 51, 63, 39, 51, 66, 33, 51, 54,
       51, 39, 45, 49, 63, 66, 61, 64, 43, 48, 41, 39, 51, 39, 63, 58, 50,
       34, 45, 40, 45, 47, 53, 65, 60, 51, 57, 54, 52, 59, 38, 42, 50, 58,
       55, 50, 56, 59, 53, 64, 60, 63, 53, 43, 58, 59, 58, 41, 63, 35, 60,
       38, 61, 45, 49, 39

In [14]:
# tipo de dato de x
type(x)

numpy.ndarray

In [ ]:
# # Estudiar las funciones de interes del submodulo random
# 'beta',
#  'binomial',
#  'bit_generator',
#  'bytes',
#  'chisquare',
#  'choice',
#  'default_rng',
#  'dirichlet',
#  'exponential',
#  'f',
#  'gamma',
#  'geometric',
#  'get_bit_generator',
#  'get_state',
#  'gumbel',
#  'hypergeometric',
#  'laplace',
#  'logistic',
#  'lognormal',
#  'logseries',
#  'mtrand',
#  'multinomial',
#  'multivariate_normal',
#  'negative_binomial',
#  'noncentral_chisquare',
#  'noncentral_f',
#  'normal',
#  'pareto',
#  'permutation',
#  'poisson',
#  'power',
#  'rand',
#  'randint',
#  'randn',
#  'random',
#  'random_integers',
#  'random_sample',
#  'ranf',
#  'rayleigh',
#  'sample',
#  'seed',
#  'set_bit_generator',
#  'set_state',
#  'shuffle',
#  'standard_cauchy',
#  'standard_exponential',
#  'standard_gamma',
#  'standard_normal',
#  'standard_t',
#  'test',
#  'triangular',
#  'uniform',
#  'vonmises',
#  'wald',
#  'weibull',
#  'zipf'

In [15]:
# Construyamos una matriz de 1000x1000 usando la funcion vonmises del submodulo
# random

# Documentacion
help(np.random.vonmises)

Help on built-in function vonmises:

vonmises(...) method of numpy.random.mtrand.RandomState instance
    vonmises(mu, kappa, size=None)
    
    Draw samples from a von Mises distribution.
    
    Samples are drawn from a von Mises distribution with specified mode
    (mu) and dispersion (kappa), on the interval [-pi, pi].
    
    The von Mises distribution (also known as the circular normal
    distribution) is a continuous probability distribution on the unit
    circle.  It may be thought of as the circular analogue of the normal
    distribution.
    
    .. note::
        New code should use the `~numpy.random.Generator.vonmises`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    mu : float or array_like of floats
        Mode ("center") of the distribution.
    kappa : float or array_like of floats
        Dispersion of the distribution, has to be >=0.
    size : int or tuple 

In [16]:
mat1 = np.random.vonmises(3.14, 9.81, size = (10**3, 10**3))
mat1

array([[-3.12604736,  2.5910023 ,  2.98216108, ..., -2.95856359,
         2.79104795,  3.13973261],
       [-2.94910723, -3.08313387,  2.84013627, ..., -2.83908732,
        -2.68164349,  3.02830809],
       [-2.83442092,  3.1364886 , -3.0759565 , ...,  2.65134197,
        -2.82677705,  3.12409755],
       ...,
       [-3.00966628,  2.90845483, -3.02885251, ...,  2.89609211,
         3.05538867,  3.11064135],
       [-2.37508573,  2.67243538,  2.67548433, ...,  3.09824614,
        -2.8969671 , -2.72634891],
       [-2.66750957,  3.04475065, -2.99086507, ..., -2.92870097,
        -2.49156493, -2.83278542]])

In [17]:
# Acceso al elemento de indice 18,19
mat1[18,19]

-3.0525362904517097

In [18]:
# Segunda fila
mat1[1, :]

array([-2.94910723, -3.08313387,  2.84013627,  3.12567244, -2.94181646,
       -3.06054916,  2.98539311,  3.04458878,  2.46971643, -3.06616756,
        2.87079387, -3.0668887 , -3.04739278, -3.1042069 , -3.05822287,
        3.09652746, -3.0413883 , -2.79149664,  3.00479401, -2.98013542,
        3.04014343,  2.99963305, -3.05567631,  2.92996074, -2.94193579,
        3.08967334, -3.10155232, -3.09090886, -3.07246202, -2.78248506,
        3.08631371,  2.97937315,  2.86836978,  3.14045156,  2.50043439,
        3.09617773, -2.90202094,  2.87471185,  2.8398657 ,  2.49238421,
       -2.85863365, -2.68292936, -2.96231231,  3.10030214,  3.13255991,
        3.1018613 ,  2.97472609, -3.12749082, -2.90132369,  3.11488734,
        2.80919113, -3.11565153,  2.44393328,  2.9304245 ,  2.85209172,
        2.59945921, -3.06630603, -2.32305782, -2.73090939,  3.06675381,
       -3.12255009,  2.45774711, -2.48589672, -2.88940836, -2.50045288,
        2.84217822, -2.82624941, -3.09595581, -2.94985883, -3.10

In [19]:
# tipo de dato de mat1
type(mat1)

numpy.ndarray

In [20]:
# Construir a partir de listas un objeto de tipo ndarray
vector1 = np.array([12,18,2,3,4])
vector1

array([12, 18,  2,  3,  4])

In [21]:
listaDatos = [[1 , 0],[3,8]]
matNotas = np.array(listaDatos)
matNotas

array([[1, 0],
       [3, 8]])

In [22]:
# LIsta elementos/componentes del submodulo linalg
dir(np.linalg)

['LinAlgError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_umath_linalg',
 'cholesky',
 'cond',
 'det',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'inv',
 'linalg',
 'lstsq',
 'matrix_power',
 'matrix_rank',
 'multi_dot',
 'norm',
 'pinv',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'tensorinv',
 'tensorsolve',
 'test']

In [23]:
# Documentacion de la funcion inv
help(np.linalg.inv)

Help on _ArrayFunctionDispatcher in module numpy.linalg:

inv(a)
    Compute the (multiplicative) inverse of a matrix.
    
    Given a square matrix `a`, return the matrix `ainv` satisfying
    ``dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])``.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Matrix to be inverted.
    
    Returns
    -------
    ainv : (..., M, M) ndarray or matrix
        (Multiplicative) inverse of the matrix `a`.
    
    Raises
    ------
    LinAlgError
        If `a` is not square or inversion fails.
    
    See Also
    --------
    scipy.linalg.inv : Similar function in SciPy.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    Examples
    --------
    >>> from numpy.linalg import inv
    >>> a = np.array([[1., 2.], [3., 4.]])
    >>> ainv = inv(a)
    >>> np.allclose(np.dot(a, ainv), np.eye(2))
    True
    >>> np.allclose(np.do

In [25]:
# Calculemos la inversa de la matriz matNotas
matInv = np.linalg.inv(matNotas)
matInv

array([[ 1.   ,  0.   ],
       [-0.375,  0.125]])

In [26]:
# Cumple la definicion operativa de la matriz inversa
np.dot(matNotas, matInv)

array([[1., 0.],
       [0., 1.]])

In [28]:
# Calculemos la inversa de mat1
Inversa_mat1 = np.linalg.inv(mat1)
Inversa_mat1

array([[-3.70038610e-02, -2.48364318e-02, -3.01618841e-02, ...,
        -2.90299862e-02, -4.68578046e-02, -3.88312999e-02],
       [-2.42966629e-05, -4.74947435e-03, -3.18120256e-03, ...,
         5.28383760e-03, -1.09388321e-02, -8.68951185e-03],
       [ 1.55934894e-01,  4.93610372e-02,  9.42016265e-02, ...,
         1.29349144e-01,  7.58072333e-02,  1.34546312e-01],
       ...,
       [ 5.46455963e-02,  1.10221043e-02,  2.94856048e-02, ...,
         5.43022393e-02,  2.91497458e-02,  5.66750225e-02],
       [ 5.81908540e-02,  3.13328192e-02,  2.90026348e-02, ...,
         2.39365428e-02,  5.87201509e-02,  4.71737219e-02],
       [-4.90308936e-02, -8.87172266e-03, -2.75504025e-02, ...,
        -3.18854505e-02, -1.91387337e-02, -3.46028255e-02]])

In [29]:
# Verifiquemos
np.dot(mat1, Inversa_mat1)

array([[ 1.00000000e+00,  3.01980663e-14,  6.75015599e-14, ...,
        -6.79456491e-14,  5.90638649e-14,  1.54098956e-13],
       [-5.32907052e-14,  1.00000000e+00, -2.84217094e-14, ...,
         2.93098879e-14, -8.12683254e-14, -1.15463195e-13],
       [-4.97379915e-14, -5.12367926e-14,  1.00000000e+00, ...,
        -2.35811370e-13,  3.80806497e-14, -7.68274333e-14],
       ...,
       [-3.99680289e-14, -1.36557432e-14,  8.65973959e-15, ...,
         1.00000000e+00, -5.12923037e-14, -4.08562073e-14],
       [ 8.43769499e-14,  1.99840144e-14,  8.88178420e-15, ...,
         2.22044605e-15,  1.00000000e+00, -1.85629290e-13],
       [ 1.69309011e-13,  2.78943535e-14,  3.99541511e-14, ...,
        -2.33146835e-15,  4.96269692e-14,  1.00000000e+00]])